service: hello

provider:
  name: aws
  region: eu-west-1
  runtime: python3.7

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - dev
    debug: true
